# Codecov Configuration
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "60...100"

  status:
    project:
      default:
        # Require 60% coverage
        target: 60%
        threshold: 5%
        informational: false
    patch:
      default:
        # New code should have at least 50% coverage
        target: 50%
        threshold: 10%

# Ignore certain paths from coverage
ignore:
  - "test/**/*"
  - "docs/**/*"
  - "macos/**/*"
  - ".github/**/*"
  - "**/*.md"
  - "**/*.json"
  - "Brewfile"
  - ".gitignore"

# Comment configuration for PRs
comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
  require_base: false
  require_head: true

# Flags for different test types
flags:
  unit:
    paths:
      - vault/
      - zsh/
    carryforward: true
  integration:
    paths:
      - vault/
      - "*.sh"
    carryforward: true
