#!/usr/bin/env bash
#
# discover-settings.sh - Capture current macOS settings
#
# Usage:
#   ./discover-settings.sh                    # Interactive mode
#   ./discover-settings.sh --all              # Dump all known domains
#   ./discover-settings.sh --diff             # Show what changed since last snapshot
#   ./discover-settings.sh --domain <name>    # Dump specific domain
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SNAPSHOT_DIR="$SCRIPT_DIR/snapshots"
SETTINGS_FILE="$SCRIPT_DIR/settings.sh"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Common preference domains to check
DOMAINS=(
    "com.apple.AppleMultitouchTrackpad"
    "com.apple.driver.AppleBluetoothMultitouch.trackpad"
    "com.apple.AppleMultitouchMouse"
    "com.apple.driver.AppleBluetoothMultitouch.mouse"
    "com.apple.mouse"
    "com.apple.keyboard"
    "com.apple.HIToolbox"
    "com.apple.dock"
    "com.apple.finder"
    "com.apple.menuextra.clock"
    "com.apple.screencapture"
    "com.apple.screensaver"
    "com.apple.desktopservices"
    "com.apple.ActivityMonitor"
    "com.apple.TextEdit"
    "com.apple.Terminal"
    "NSGlobalDomain"
)

mkdir -p "$SNAPSHOT_DIR"

usage() {
    echo "Usage: $0 [options]"
    echo ""
    echo "Options:"
    echo "  --all              Dump all known preference domains"
    echo "  --diff             Compare current settings to last snapshot"
    echo "  --domain <name>    Dump a specific domain"
    echo "  --snapshot         Create a snapshot of current settings"
    echo "  --list-domains     List all preference domains on this system"
    echo "  --generate         Generate settings.sh from current preferences"
    echo "  -h, --help         Show this help"
    echo ""
    echo "Examples:"
    echo "  $0 --snapshot              # Save current state"
    echo "  # Change settings in System Preferences..."
    echo "  $0 --diff                  # See what changed"
    echo "  $0 --generate              # Generate apply script"
}

# Create a snapshot of current settings
snapshot() {
    local timestamp
    timestamp=$(date +%Y%m%d_%H%M%S)
    local snapshot_file="$SNAPSHOT_DIR/snapshot_$timestamp.txt"

    echo -e "${BLUE}Creating snapshot...${NC}"

    for domain in "${DOMAINS[@]}"; do
        echo "=== $domain ===" >> "$snapshot_file"
        defaults read "$domain" 2>/dev/null >> "$snapshot_file" || echo "(not found)" >> "$snapshot_file"
        echo "" >> "$snapshot_file"
    done

    # Also capture global domain
    echo "=== NSGlobalDomain ===" >> "$snapshot_file"
    defaults read NSGlobalDomain >> "$snapshot_file" 2>/dev/null

    # Create/update "latest" symlink
    ln -sf "$snapshot_file" "$SNAPSHOT_DIR/latest.txt"

    echo -e "${GREEN}Snapshot saved: $snapshot_file${NC}"
    echo -e "Symlinked to: $SNAPSHOT_DIR/latest.txt"
}

# Compare current settings to last snapshot
diff_settings() {
    if [[ ! -f "$SNAPSHOT_DIR/latest.txt" ]]; then
        echo -e "${RED}No snapshot found. Run with --snapshot first.${NC}"
        exit 1
    fi

    local temp_current
    temp_current=$(mktemp)

    echo -e "${BLUE}Comparing to last snapshot...${NC}"

    for domain in "${DOMAINS[@]}"; do
        echo "=== $domain ===" >> "$temp_current"
        defaults read "$domain" 2>/dev/null >> "$temp_current" || echo "(not found)" >> "$temp_current"
        echo "" >> "$temp_current"
    done

    echo "=== NSGlobalDomain ===" >> "$temp_current"
    defaults read NSGlobalDomain >> "$temp_current" 2>/dev/null

    if diff -u "$SNAPSHOT_DIR/latest.txt" "$temp_current"; then
        echo -e "${GREEN}No changes detected.${NC}"
    else
        echo ""
        echo -e "${YELLOW}Changes detected above.${NC}"
        echo "Run with --generate to create/update settings.sh"
    fi

    rm -f "$temp_current"
}

# Dump a specific domain
dump_domain() {
    local domain="$1"
    echo -e "${BLUE}=== $domain ===${NC}"
    defaults read "$domain" 2>/dev/null || echo -e "${RED}Domain not found${NC}"
}

# Dump all known domains
dump_all() {
    for domain in "${DOMAINS[@]}"; do
        echo -e "${BLUE}=== $domain ===${NC}"
        defaults read "$domain" 2>/dev/null || echo "(not found)"
        echo ""
    done
}

# List all preference domains on the system
list_domains() {
    echo -e "${BLUE}User preference domains:${NC}"
    defaults domains | tr ',' '\n' | sed 's/^ *//' | sort
    echo ""
    echo -e "${BLUE}Tip: Use 'defaults read <domain>' to inspect any domain${NC}"
}

# Generate settings.sh from common preferences
generate_settings() {
    echo -e "${BLUE}Generating $SETTINGS_FILE...${NC}"

    cat > "$SETTINGS_FILE" << 'HEADER'
#!/usr/bin/env bash
#
# macOS System Settings
#
# Apply with: ./apply-settings.sh
# Generated by: ./discover-settings.sh --generate
#
# WARNING: Review these settings before applying!
# Some settings require logout/restart to take effect.
#
set -euo pipefail

echo "Applying macOS settings..."

# Close System Preferences to prevent conflicts
osascript -e 'tell application "System Preferences" to quit' 2>/dev/null || true

###############################################################################
# Trackpad                                                                    #
###############################################################################

HEADER

    # Trackpad settings
    echo "# Tap to click" >> "$SETTINGS_FILE"
    local tap_click
    tap_click=$(defaults read com.apple.AppleMultitouchTrackpad Clicking 2>/dev/null || echo "0")
    echo "defaults write com.apple.AppleMultitouchTrackpad Clicking -bool $([[ $tap_click == "1" ]] && echo "true" || echo "false")" >> "$SETTINGS_FILE"

    echo "" >> "$SETTINGS_FILE"
    echo "# Tracking speed (0-3, where 3 is fastest)" >> "$SETTINGS_FILE"
    local track_speed
    track_speed=$(defaults read NSGlobalDomain com.apple.trackpad.scaling 2>/dev/null || echo "1")
    echo "defaults write NSGlobalDomain com.apple.trackpad.scaling -float $track_speed" >> "$SETTINGS_FILE"

    echo "" >> "$SETTINGS_FILE"
    echo "# Three finger drag" >> "$SETTINGS_FILE"
    local three_drag
    three_drag=$(defaults read com.apple.AppleMultitouchTrackpad TrackpadThreeFingerDrag 2>/dev/null || echo "0")
    echo "defaults write com.apple.AppleMultitouchTrackpad TrackpadThreeFingerDrag -bool $([[ $three_drag == "1" ]] && echo "true" || echo "false")" >> "$SETTINGS_FILE"
    echo "defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadThreeFingerDrag -bool $([[ $three_drag == "1" ]] && echo "true" || echo "false")" >> "$SETTINGS_FILE"

    echo "" >> "$SETTINGS_FILE"
    echo "# Natural scrolling" >> "$SETTINGS_FILE"
    local natural
    natural=$(defaults read NSGlobalDomain com.apple.swipescrolldirection 2>/dev/null || echo "1")
    echo "defaults write NSGlobalDomain com.apple.swipescrolldirection -bool $([[ $natural == "1" ]] && echo "true" || echo "false")" >> "$SETTINGS_FILE"

    cat >> "$SETTINGS_FILE" << 'MOUSE'

###############################################################################
# Mouse                                                                       #
###############################################################################

MOUSE

    echo "# Mouse tracking speed" >> "$SETTINGS_FILE"
    local mouse_speed
    mouse_speed=$(defaults read NSGlobalDomain com.apple.mouse.scaling 2>/dev/null || echo "1")
    echo "defaults write NSGlobalDomain com.apple.mouse.scaling -float $mouse_speed" >> "$SETTINGS_FILE"

    cat >> "$SETTINGS_FILE" << 'KEYBOARD'

###############################################################################
# Keyboard                                                                    #
###############################################################################

KEYBOARD

    echo "# Key repeat rate (lower = faster, default 2)" >> "$SETTINGS_FILE"
    local key_repeat
    key_repeat=$(defaults read NSGlobalDomain KeyRepeat 2>/dev/null || echo "2")
    echo "defaults write NSGlobalDomain KeyRepeat -int $key_repeat" >> "$SETTINGS_FILE"

    echo "" >> "$SETTINGS_FILE"
    echo "# Delay until repeat (lower = shorter, default 15)" >> "$SETTINGS_FILE"
    local init_repeat
    init_repeat=$(defaults read NSGlobalDomain InitialKeyRepeat 2>/dev/null || echo "15")
    echo "defaults write NSGlobalDomain InitialKeyRepeat -int $init_repeat" >> "$SETTINGS_FILE"

    echo "" >> "$SETTINGS_FILE"
    echo "# Disable auto-correct" >> "$SETTINGS_FILE"
    local autocorrect
    autocorrect=$(defaults read NSGlobalDomain NSAutomaticSpellingCorrectionEnabled 2>/dev/null || echo "1")
    echo "defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool $([[ $autocorrect == "1" ]] && echo "true" || echo "false")" >> "$SETTINGS_FILE"

    cat >> "$SETTINGS_FILE" << 'DOCK'

###############################################################################
# Dock                                                                        #
###############################################################################

DOCK

    echo "# Dock icon size" >> "$SETTINGS_FILE"
    local dock_size
    dock_size=$(defaults read com.apple.dock tilesize 2>/dev/null || echo "48")
    echo "defaults write com.apple.dock tilesize -int $dock_size" >> "$SETTINGS_FILE"

    echo "" >> "$SETTINGS_FILE"
    echo "# Auto-hide dock" >> "$SETTINGS_FILE"
    local autohide
    autohide=$(defaults read com.apple.dock autohide 2>/dev/null || echo "0")
    echo "defaults write com.apple.dock autohide -bool $([[ $autohide == "1" ]] && echo "true" || echo "false")" >> "$SETTINGS_FILE"

    echo "" >> "$SETTINGS_FILE"
    echo "# Show recent apps in Dock" >> "$SETTINGS_FILE"
    local recent
    recent=$(defaults read com.apple.dock show-recents 2>/dev/null || echo "1")
    echo "defaults write com.apple.dock show-recents -bool $([[ $recent == "1" ]] && echo "true" || echo "false")" >> "$SETTINGS_FILE"

    echo "" >> "$SETTINGS_FILE"
    echo "# Minimize windows to application icon" >> "$SETTINGS_FILE"
    local min_to_app
    min_to_app=$(defaults read com.apple.dock minimize-to-application 2>/dev/null || echo "0")
    echo "defaults write com.apple.dock minimize-to-application -bool $([[ $min_to_app == "1" ]] && echo "true" || echo "false")" >> "$SETTINGS_FILE"

    cat >> "$SETTINGS_FILE" << 'FINDER'

###############################################################################
# Finder                                                                      #
###############################################################################

FINDER

    echo "# Show all file extensions" >> "$SETTINGS_FILE"
    local show_ext
    show_ext=$(defaults read NSGlobalDomain AppleShowAllExtensions 2>/dev/null || echo "0")
    echo "defaults write NSGlobalDomain AppleShowAllExtensions -bool $([[ $show_ext == "1" ]] && echo "true" || echo "false")" >> "$SETTINGS_FILE"

    echo "" >> "$SETTINGS_FILE"
    echo "# Show hidden files" >> "$SETTINGS_FILE"
    local show_hidden
    show_hidden=$(defaults read com.apple.finder AppleShowAllFiles 2>/dev/null || echo "0")
    echo "defaults write com.apple.finder AppleShowAllFiles -bool $([[ $show_hidden == "1" ]] && echo "true" || echo "false")" >> "$SETTINGS_FILE"

    echo "" >> "$SETTINGS_FILE"
    echo "# Show path bar" >> "$SETTINGS_FILE"
    local path_bar
    path_bar=$(defaults read com.apple.finder ShowPathbar 2>/dev/null || echo "0")
    echo "defaults write com.apple.finder ShowPathbar -bool $([[ $path_bar == "1" ]] && echo "true" || echo "false")" >> "$SETTINGS_FILE"

    echo "" >> "$SETTINGS_FILE"
    echo "# Show status bar" >> "$SETTINGS_FILE"
    local status_bar
    status_bar=$(defaults read com.apple.finder ShowStatusBar 2>/dev/null || echo "0")
    echo "defaults write com.apple.finder ShowStatusBar -bool $([[ $status_bar == "1" ]] && echo "true" || echo "false")" >> "$SETTINGS_FILE"

    echo "" >> "$SETTINGS_FILE"
    echo "# Disable .DS_Store on network/USB volumes" >> "$SETTINGS_FILE"
    local ds_net
    ds_net=$(defaults read com.apple.desktopservices DSDontWriteNetworkStores 2>/dev/null || echo "0")
    echo "defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool $([[ $ds_net == "1" ]] && echo "true" || echo "false")" >> "$SETTINGS_FILE"
    local ds_usb
    ds_usb=$(defaults read com.apple.desktopservices DSDontWriteUSBStores 2>/dev/null || echo "0")
    echo "defaults write com.apple.desktopservices DSDontWriteUSBStores -bool $([[ $ds_usb == "1" ]] && echo "true" || echo "false")" >> "$SETTINGS_FILE"

    cat >> "$SETTINGS_FILE" << 'SCREENSHOTS'

###############################################################################
# Screenshots                                                                 #
###############################################################################

SCREENSHOTS

    echo "# Screenshot location" >> "$SETTINGS_FILE"
    local ss_loc
    ss_loc=$(defaults read com.apple.screencapture location 2>/dev/null || echo "$HOME/Desktop")
    echo "defaults write com.apple.screencapture location -string \"$ss_loc\"" >> "$SETTINGS_FILE"

    echo "" >> "$SETTINGS_FILE"
    echo "# Screenshot format (png, jpg, pdf, etc)" >> "$SETTINGS_FILE"
    local ss_fmt
    ss_fmt=$(defaults read com.apple.screencapture type 2>/dev/null || echo "png")
    echo "defaults write com.apple.screencapture type -string \"$ss_fmt\"" >> "$SETTINGS_FILE"

    echo "" >> "$SETTINGS_FILE"
    echo "# Disable screenshot shadow" >> "$SETTINGS_FILE"
    local ss_shadow
    ss_shadow=$(defaults read com.apple.screencapture disable-shadow 2>/dev/null || echo "0")
    echo "defaults write com.apple.screencapture disable-shadow -bool $([[ $ss_shadow == "1" ]] && echo "true" || echo "false")" >> "$SETTINGS_FILE"

    cat >> "$SETTINGS_FILE" << 'MISC'

###############################################################################
# Misc                                                                        #
###############################################################################

# Expand save panel by default
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode2 -bool true

# Expand print panel by default
defaults write NSGlobalDomain PMPrintingExpandedStateForPrint -bool true
defaults write NSGlobalDomain PMPrintingExpandedStateForPrint2 -bool true

###############################################################################
# Apply Changes                                                               #
###############################################################################

echo ""
echo "Restarting affected applications..."

# Restart Dock
killall Dock 2>/dev/null || true

# Restart Finder
killall Finder 2>/dev/null || true

echo ""
echo "Done! Some changes may require logout/restart."
MISC

    chmod +x "$SETTINGS_FILE"
    echo -e "${GREEN}Generated: $SETTINGS_FILE${NC}"
    echo ""
    echo "Review the file, then run: ./apply-settings.sh"
}

# Main
case "${1:-}" in
    --all)
        dump_all
        ;;
    --diff)
        diff_settings
        ;;
    --domain)
        if [[ -z "${2:-}" ]]; then
            echo "Error: --domain requires a domain name"
            exit 1
        fi
        dump_domain "$2"
        ;;
    --snapshot)
        snapshot
        ;;
    --list-domains)
        list_domains
        ;;
    --generate)
        generate_settings
        ;;
    -h|--help)
        usage
        ;;
    "")
        echo "macOS Settings Discovery Tool"
        echo ""
        echo "Workflow:"
        echo "  1. Run: $0 --snapshot"
        echo "  2. Change settings in System Preferences"
        echo "  3. Run: $0 --diff"
        echo "  4. Run: $0 --generate"
        echo ""
        usage
        ;;
    *)
        echo "Unknown option: $1"
        usage
        exit 1
        ;;
esac
