#!/usr/bin/env bash
# ============================================================
# FILE: vault/restore-env.sh
# Restores environment secrets from Bitwarden Secure Notes
# ============================================================
set -euo pipefail

# Accept session from argument or environment variable
SESSION="${1:-${BW_SESSION:-}}"

if [[ -z "$SESSION" ]]; then
  echo "restore-env.sh: BW_SESSION or session argument is required." >&2
  exit 1
fi

# Verify jq is available
if ! command -v jq >/dev/null 2>&1; then
  echo "restore-env.sh: 'jq' is required but not installed." >&2
  exit 1
fi

LOCAL_DIR="$HOME/.local"
ENV_FILE="$LOCAL_DIR/env.secrets"
LOADER_FILE="$LOCAL_DIR/load-env.sh"

mkdir -p "$LOCAL_DIR"

echo "Restoring environment secrets from Bitwarden item: Environment-Secrets"

# Fetch item from Bitwarden (graceful failure if not found)
json=""
if ! json="$(bw get item "Environment-Secrets" --session "$SESSION" 2>/dev/null)"; then
    echo "  [SKIP] Item 'Environment-Secrets' not found in Bitwarden."
    exit 0
fi

# Extract notes field (expects KEY=VALUE format, one per line)
notes="$(printf '%s\n' "$json" | jq -r '.notes // ""')"
if [[ -z "$notes" || "$notes" == "null" ]]; then
    echo "  [SKIP] Item 'Environment-Secrets' has empty notes."
    exit 0
fi

# Write secrets file with secure permissions
printf '%s\n' "$notes" > "$ENV_FILE"
chmod 600 "$ENV_FILE"

# Create loader script that properly handles values with spaces/special chars
cat > "$LOADER_FILE" << 'LOADER'
#!/usr/bin/env bash
# Auto-generated by restore-env.sh
# Source this file to load environment secrets: source ~/.local/load-env.sh

ENV_FILE="$HOME/.local/env.secrets"

if [[ -f "$ENV_FILE" ]]; then
    while IFS= read -r line || [[ -n "$line" ]]; do
        # Skip empty lines and comments
        [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]] && continue
        # Export the variable
        export "$line"
    done < "$ENV_FILE"
fi
LOADER

chmod 700 "$LOADER_FILE"

echo "  [OK] Restored: $ENV_FILE"
echo "  [OK] Created:  $LOADER_FILE"
echo ""
echo "To load secrets in your shell, run:"
echo "  source ~/.local/load-env.sh"
