#!/usr/bin/env zsh
# ============================================================
# FILE: vault/restore-env.sh
# Restores environment secrets from Bitwarden Secure Notes
# ============================================================
set -euo pipefail

# Source common functions
source "$(dirname "$0")/_common.sh"

# Accept session from argument or environment variable
SESSION="${1:-${BW_SESSION:-}}"

if [[ -z "$SESSION" ]]; then
    fail "restore-env.sh: BW_SESSION or session argument is required."
    exit 1
fi

# Verify jq is available
require_jq

LOCAL_DIR="$HOME/.local"
ENV_FILE="$LOCAL_DIR/env.secrets"
LOADER_FILE="$LOCAL_DIR/load-env.sh"

mkdir -p "$LOCAL_DIR"

echo "Restoring environment secrets from Bitwarden item: Environment-Secrets"

# Fetch item from Bitwarden (graceful failure if not found)
json=$(bw_get_item "Environment-Secrets" "$SESSION")
if [[ -z "$json" ]]; then
    echo "  [SKIP] Item 'Environment-Secrets' not found in Bitwarden."
    exit 0
fi

# Extract notes field (expects KEY=VALUE format, one per line)
notes="$(printf '%s\n' "$json" | jq -r '.notes // ""')"
if [[ -z "$notes" || "$notes" == "null" ]]; then
    echo "  [SKIP] Item 'Environment-Secrets' has empty notes."
    exit 0
fi

# Validate KEY=VALUE format (warn about malformed lines)
invalid_lines=0
while IFS= read -r line || [[ -n "$line" ]]; do
    # Skip empty lines and comments
    [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]] && continue
    # Check for KEY=VALUE format (KEY must start with letter/underscore)
    if ! [[ "$line" =~ ^[A-Za-z_][A-Za-z0-9_]*= ]]; then
        warn "Malformed line (expected KEY=VALUE): $line"
        ((invalid_lines++))
    fi
done <<< "$notes"

if [[ $invalid_lines -gt 0 ]]; then
    warn "$invalid_lines malformed line(s) found in Environment-Secrets"
fi

# Backup existing secrets file if present
if [[ -f "$ENV_FILE" ]]; then
    cp "$ENV_FILE" "${ENV_FILE}.bak-$(date +%Y%m%d%H%M%S)"
    info "Backed up existing secrets file."
fi

# Write secrets file with secure permissions
printf '%s\n' "$notes" > "$ENV_FILE"
chmod 600 "$ENV_FILE"

# Create loader script that properly handles values with spaces/special chars
cat > "$LOADER_FILE" << 'LOADER'
#!/usr/bin/env bash
# Auto-generated by restore-env.sh
# Source this file to load environment secrets: source ~/.local/load-env.sh

ENV_FILE="$HOME/.local/env.secrets"

if [[ -f "$ENV_FILE" ]]; then
    while IFS= read -r line || [[ -n "$line" ]]; do
        # Skip empty lines and comments
        [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]] && continue
        # Export the variable
        export "$line"
    done < "$ENV_FILE"
fi
LOADER

chmod 700 "$LOADER_FILE"

pass "Restored: $ENV_FILE"
pass "Created:  $LOADER_FILE"
echo ""
echo "To load secrets in your shell, run:"
echo "  source ~/.local/load-env.sh"
